import '../styles/index.scss'

import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Inter, Sen } from 'next/font/google'
import { NextIntlClientProvider, useMessages } from 'next-intl'

import { Header } from '../components/shared/Header'

const inter = Inter({ subsets: ['latin'], weight: ['900', '700', '400', '500'], variable: '--font-inter' })
const sen = Sen({ subsets: ['latin'], weight: ['700', '400', '500'], variable: '--font-sen' })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: ReactNode
  params: { locale: string }
}>) {
  const messages = useMessages()

  return (
    <html lang={locale}>
      <body suppressHydrationWarning={true} className={`${inter.variable} ${sen.variable}`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header />
          <div className='container'>{children}</div>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
